# Generated by Django 2.2.6 on 2019-12-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('slname', models.CharField(max_length=30)),
                ('snumber', models.IntegerField()),
                ('semail', models.EmailField(max_length=50)),
                ('sgender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('sdob', models.DateField(max_length=8)),
                ('squalification', models.CharField(max_length=50)),
                ('sadress', models.CharField(max_length=50)),
                ('sfile', models.FileField(max_length=254, upload_to=None)),
            ],
        ),
    ]
