# Generated by Django 2.2.6 on 2019-12-01 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191201_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='spassword',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
