# Generated by Django 2.2.6 on 2019-12-01 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_spassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='susername',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
