# Generated by Django 2.2.6 on 2019-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student_susername'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('slname', models.CharField(max_length=30)),
                ('snumber', models.IntegerField()),
                ('semail', models.EmailField(max_length=50)),
                ('susername', models.CharField(max_length=50)),
                ('spassword', models.SlugField()),
                ('sgender', models.CharField(max_length=128)),
                ('sdob', models.CharField(max_length=50)),
                ('squalification', models.CharField(max_length=50)),
                ('sadress', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
