# Generated by Django 2.2.6 on 2019-12-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20191201_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='student',
        ),
    ]
