# Generated by Django 2.2.6 on 2020-01-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20191202_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scountry',
            field=models.CharField(default='now', max_length=30),
            preserve_default=False,
        ),
    ]
